[BACKPORT] kernel: ktime.h: Introduce ktime_ms_delta
This patch adds a reusable time difference function which returns the
difference in millisecond, as often used in some driver code, e.g.
mtd/test, media/rc, etc.

* Aquarius223: Change Linux 3.18.y kernel msm8996 kernel
* Fix F2FS Merge Build error:
 ../fs/f2fs/checkpoint.c:1708:15: error: implicit declaration of function 'ktime_ms_delta' [-Werror,-Wimplicit-function-declaration]
                diff = (u64)ktime_ms_delta(ktime_get(), req->queue_time);
                            ^
../fs/f2fs/checkpoint.c:1708:15: note: did you mean 'ktime_us_delta'?
../include/linux/ktime.h:209:19: note: 'ktime_us_delta' declared here
static inline s64 ktime_us_delta(const ktime_t later, const ktime_t earlier)
                  ^
1 error generated.

Signed-off-by: Chunyan Zhang <zhang.chunyan@linaro.org>
Acked-by: Arnd Bergmann <arnd@linaro.org>
Cc: zhang.lyra@gmail.com
Cc: davem@davemloft.net
Cc: john.stultz@linaro.org
Cc: dborkman@redhat.com
Link: http://lkml.kernel.org/r/1418793095-18780-1-git-send-email-zhang.chunyan@linaro.org
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Change-Id: Ic853429a0573e1b5a57db2f024b3c9dabdc6cc58